image: archlinux
packages:
  - texlive-most
sources:
  - https://git.sr.ht/~chandlerswift/resume
secrets:
  - b574f16c-5c53-411a-98c0-05ac0061dbce
tasks:
  - build: |
      cd resume
      make
  - publish: |
      set +x
      cd resume
      git describe --exact-match && \
      curl \
        -H "Authorization: token `cat ~/.oauth_token`" \
        -F "file=@resume.pdf;filename=chandlerswift-`date +%F`.pdf" \
        https://git.sr.ht/api/repos/resume/artifacts/`git describe`|| true
artifacts:
  - resume/resume.pdf
